INSERT INTO projects (name, description, category, project_url, thumbnail_url, tech_stack) VALUES 
('Day 1 : PDF Toolkit', 'Merge, split, and compress PDFs in one place using file handling libraries or APIs', 'File Tools', '#', '', ARRAY['HTML', 'CSS', 'JavaScript', 'React']::TEXT[]),
('Day 2 : Image Compressor', 'Upload an image and reduce its size while showing before/after comparison', 'Image Tools', '#', '', ARRAY['HTML', 'CSS', 'JavaScript', 'React']::TEXT[]),
('Day 3 : Color Palette Extractor', 'Extract dominant colors from an image and display hex codes', 'Image Tools', '#', '', ARRAY['HTML', 'CSS', 'JavaScript', 'React']::TEXT[]),
('Day 4 : Background Remover', 'Remove image backgrounds using an API like remove.bg', 'Image Tools', '#', '', ARRAY['HTML', 'CSS', 'JavaScript', 'React', 'API']::TEXT[]),
('Day 5 : File Converter', 'Convert between formats like JPG ↔ PNG or PDF ↔ image', 'File Tools', '#', '', ARRAY['HTML', 'CSS', 'JavaScript', 'React']::TEXT[]),
('Day 6 : Code Snippet Manager', 'Save, tag, search, and reuse code snippets', 'Developer Tools', '#', '', ARRAY['HTML', 'CSS', 'JavaScript', 'React', 'Supabase']::TEXT[]),
('Day 7 : JSON Formatter + Validator', 'Format messy JSON and highlight syntax errors', 'Developer Tools', '#', '', ARRAY['HTML', 'CSS', 'JavaScript', 'React']::TEXT[]),
('Day 8 : Markdown Editor', 'Write markdown with live preview and export to HTML/PDF', 'Developer Tools', '#', '', ARRAY['HTML', 'CSS', 'JavaScript', 'React']::TEXT[]),
('Day 9 : Regex Tester', 'Test regex patterns against input strings with match highlights', 'Developer Tools', '#', '', ARRAY['HTML', 'CSS', 'JavaScript', 'React']::TEXT[]),
('Day 10 : API Tester', 'Send GET/POST requests and view responses like a mini Postman', 'Developer Tools', '#', '', ARRAY['HTML', 'CSS', 'JavaScript', 'React']::TEXT[]),
('Day 11 : AI Chatbot', 'Fully working chatbot with memory using an AI API', 'AI Tools', '#', '', ARRAY['HTML', 'CSS', 'JavaScript', 'React', 'API', 'AI']::TEXT[]),
('Day 12 : AI Text Summarizer', 'Paste long text and generate a concise summary', 'AI Tools', '#', '', ARRAY['HTML', 'CSS', 'JavaScript', 'React', 'API', 'AI']::TEXT[]),
('Day 13 : AI Resume Improver', 'Upload or paste resume and get improvement suggestions', 'AI Tools', '#', '', ARRAY['HTML', 'CSS', 'JavaScript', 'React', 'API', 'AI']::TEXT[]),
('Day 14 : AI Email Writer', 'Generate professional emails from short prompts', 'AI Tools', '#', '', ARRAY['HTML', 'CSS', 'JavaScript', 'React', 'API', 'AI']::TEXT[]),
('Day 15 : AI Code Explainer', 'Paste code and get a human-readable explanation', 'AI Tools', '#', '', ARRAY['HTML', 'CSS', 'JavaScript', 'React', 'API', 'AI']::TEXT[]),
('Day 16 : Expense Tracker', 'Track income/expenses and visualize data with charts', 'Productivity', '#', '', ARRAY['HTML', 'CSS', 'JavaScript', 'React', 'Supabase']::TEXT[]),
('Day 17 : Smart Notes App', 'Create notes with search, tags, and categories', 'Productivity', '#', '', ARRAY['HTML', 'CSS', 'JavaScript', 'React', 'Supabase']::TEXT[]),
('Day 18 : Bookmark Manager', 'Save and organize useful links with categories', 'Productivity', '#', '', ARRAY['HTML', 'CSS', 'JavaScript', 'React', 'Supabase']::TEXT[]),
('Day 19 : Clipboard Manager', 'Store frequently copied texts for reuse', 'Productivity', '#', '', ARRAY['HTML', 'CSS', 'JavaScript', 'React']::TEXT[]),
('Day 20 : Daily Planner', 'Manage daily tasks with time-based scheduling', 'Productivity', '#', '', ARRAY['HTML', 'CSS', 'JavaScript', 'React', 'Supabase']::TEXT[]),
('Day 21 : Meme Generator', 'Create memes with custom text and image upload', 'Creative', '#', '', ARRAY['HTML', 'CSS', 'JavaScript', 'React']::TEXT[]),
('Day 22 : Image Editor', 'Basic editing like crop, resize, and filters', 'Creative', '#', '', ARRAY['HTML', 'CSS', 'JavaScript', 'React']::TEXT[]),
('Day 23 : Thumbnail Generator', 'Create YouTube-style thumbnails with templates', 'Creative', '#', '', ARRAY['HTML', 'CSS', 'JavaScript', 'React']::TEXT[]),
('Day 24 : Screenshot Annotator', 'Upload screenshots and draw or highlight areas', 'Creative', '#', '', ARRAY['HTML', 'CSS', 'JavaScript', 'React']::TEXT[]),
('Day 25 : GIF Generator', 'Convert images into GIFs with speed control', 'Creative', '#', '', ARRAY['HTML', 'CSS', 'JavaScript', 'React']::TEXT[]),
('Day 26 : Website Screenshot Tool', 'Generate screenshots of websites via API', 'Web Tools', '#', '', ARRAY['HTML', 'CSS', 'JavaScript', 'React', 'API']::TEXT[]),
('Day 27 : Meta Tag Generator', 'Create SEO meta tags for websites', 'Web Tools', '#', '', ARRAY['HTML', 'CSS', 'JavaScript', 'React']::TEXT[]),
('Day 28 : Password Manager', 'Securely store and retrieve passwords with encryption', 'Security', '#', '', ARRAY['HTML', 'CSS', 'JavaScript', 'React', 'Supabase']::TEXT[]),
('Day 29 : URL Metadata Previewer', 'Show preview (title, image, description) of links', 'Web Tools', '#', '', ARRAY['HTML', 'CSS', 'JavaScript', 'React', 'API']::TEXT[]),
('Day 30 : Form Builder', 'Create custom forms and share them with others for responses', 'Web Tools', '#', '', ARRAY['HTML', 'CSS', 'JavaScript', 'React', 'Supabase']::TEXT[]);